### ISSUE TITLE
Setting FB_REFERENCE_IMAGE_DIR via prefix-header-contents doesn't do anything

### ISSUE THREAD

**Issue by dblock** [facebook/ios-snapshot-test-case#10]
I think https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCase.podspec#L24 doesn't do anything useful. It literally sets the value to "$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages" (doesn't resolve SOURCE_ROOT for example. It also sets that on the Pod project, you want it on the test project so that the macros can pick it up.

Am I missing something?

**Comment by dstnbrkr** [comment]
Removed additional config in favor of default setting in FBSnapshotTestCase.h
