### ISSUE TITLE
Reference Image has wrong size

### ISSUE THREAD

**Issue by peacemoon** [facebook/ios-snapshot-test-case#114]
I'm trying to create reference images for views of my view controller for different devices so that I can test the screenshot of my views later.

I'm trying do something like this

```
func testLoginViewController() {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let navViewController = storyboard.instantiateInitialViewController()
    let viewController = navViewController.topViewController as! LoginViewController
    FBSnapshotVerifyView(viewController.view)
}
```
I can successfully create the reference images but all the images have the size of 640x960 although I run different simulators (iPhone 4s -> iPhone 6 Plus).

Does anyone know where the problem is?

**Comment by nscoding** [comment]
I haven't tried it with storyboards but we can figure this out. Can you try to record with `usesDrawViewHierarchyInRect`? 

```
override func setUp() {
    super.setUp()
    recordMode = true
    usesDrawViewHierarchyInRect = true
}
```

This will place your view into a UIWindow before the snapshot and it should then have the correct size.

**Comment by peacemoon** [comment]
It works correctly with my simple test project here: https://github.com/peacemoon/TestFBSnapshotTestCase but with another project, I always have a 640x960 regardless with simulator I am using. Let's me check my storyboard settings to see whether I have to set something there.

**Comment by nscoding** [comment]
even when you use `usesDrawViewHierarchyInRect` ?

**Comment by peacemoon** [comment]
yes, even when I use `usesDrawViewHierarchyInRect`. I will try to investigate further or create another sample project. I can't post  my current project because it's a company's project

**Comment by peacemoon** [comment]
After further testing, I found a very strange thing. In the "bad" project, when I try to print out the screen size using `print("SCREEN SIZE = \(UIScreen.mainScreen().bounds.size)")` ,  I always have 320x480 . In the "good" project, the printed size is simulator-dependent. I doubt this issue is related to FBSnapshotTestCase  Lib, but rather project configuration. But I will try to figure out which configuration affects this behaviour and will post here what I find.

**Comment by peacemoon** [comment]
OK, I may find something. I use FBSnapshotTestCase inside UI Testing, and not Unit Testing. Maybe the configuration for UI Testing is different than in Unit Testing. When I use the framework inside Unit Testing, the size is reported correctly. You can close this issue. Thanks

**Comment by nscoding** [comment]
thanks for the update.
