### ISSUE TITLE
Cannot Build In Xcode 7.1 

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/ios-snapshot-test-case#125]
Using Cocoapods, pointing at `~> 2.0.5`, the module will no longer build for me with the error `/Pods/FBSnapshotTestCase/FBSnapshotTestCase/FBSnapshotTestCase.h:11:9: Include of non-modular header inside framework module 'FBSnapshotTestCase.FBSnapshotTestCase'`.

It's complaining because `FBSnapshotTestCase.h` imports the non-modular header `FBSnapshotTestCasePlatform.h`. I'll look into this when I get time but if someone else can help that'd be great!

**Comment by nscoding** [comment]
Thanks for letting me know, I will look at and fix it as soon as possible. From [this stackoverflow](http://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module) thread it seems that you can disable this error. Is that something you can do until I provide a fix?

**Comment by Adlai-Holler** [comment]
Awesome, I'm glad to know you're on it! That fix isn't working for me but at the moment it's not urgent. I'll comment on here if it starts blocking work or what have you.

**Comment by nscoding** [comment]
@Adlai-Holler can you try patching #127 to see if resolves the issue for you?

**Comment by soleares** [comment]
Here's a workaround. Add this to the end of your Podfile.

```
post_install do |installer|
  `find Pods -regex 'Pods/FBSnapshotTestCase.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)FBSnapshotTestCase\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

It converts  `#import <FBSnapshotTestCase FBSnapshotTestCasePlatform.h>`  to `#import "FBSnapshotTestCasePlatform.h"` and then you should be able to build in Xcode 7.1.

See https://github.com/CocoaPods/CocoaPods/issues/4420.

**Comment by nscoding** [comment]
I just pushed 2.0.6, please confirm that your issue is resolved

**Comment by Adlai-Holler** [comment]
Works like a charm
