### ISSUE TITLE
Should FBSnapshotTestController header be public?

### ISSUE THREAD

**Issue by andreamazz** [facebook/ios-snapshot-test-case#128]
The new modulemap imports `FBSnapshotTestController` as a [private header](https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCase.modulemap#L13). This causes an issue with `Nimble-Snapshots` since it's using the class:
https://github.com/ashfurrow/Nimble-Snapshots/blob/master/HaveValidSnapshot.swift#L43  

Can we move the header as public? What do you think?

**Comment by nscoding** [comment]
I was worried about this. Yeah I will make it public since this is a breaking change for you

**Comment by andreamazz** [comment]
Awesome, thanks :+1:

**Comment by esttorhe** [comment]
Came here for the same reason actually :smile: 

Upon multiple tests this can also be accomplished via a better «umbrella header»

Here's the one generated via `CocoaPods`

```objc
#import <UIKit/UIKit.h>

#import "FBSnapshotTestCase.h"
#import "FBSnapshotTestCasePlatform.h"
#import "UIImage+Compare.h"
#import "UIImage+Diff.h"
#import "UIImage+Snapshot.h"
#import "FBSnapshotTestCase.h"
#import "FBSnapshotTestCasePlatform.h"
#import "FBSnapshotTestController.h"

FOUNDATION_EXPORT double FBSnapshotTestCaseVersionNumber;
FOUNDATION_EXPORT const unsigned char FBSnapshotTestCaseVersionString[];
```

**Comment by nscoding** [comment]
I will address this #129, do you guys need the `UIImage` categories?

**Comment by esttorhe** [comment]
Currently `Nimble-Snapshots` only needs `FBSnapshotTestController`

**Comment by nscoding** [comment]
sounds good, can someone patch and test before I merge? :construction_worker:

**Comment by esttorhe** [comment]
Just tested `Nimble-Snapshots` using `nscoding/headers` and all tests are :green_heart: 

:ok_hand: from our side

**Comment by esttorhe** [comment]
@nscoding just ping me here when `2.0.7` is released so we can release `Nimble-Snapshots` accordingly :bow: 

Thanks

**Comment by nscoding** [comment]
@esttorhe done :+1:

**Comment by esttorhe** [comment]
Thanks; `Nimble-Snapshots` v`1.2.0` is out; working and with «device agnostic» functionality :tada:

**Comment by nscoding** [comment]
:tada: I assume this is fixed and closing the issue :tada:
