### ISSUE TITLE
Xcode 7.1 warnings - umbrella header

### ISSUE THREAD

**Issue by soleares** [facebook/ios-snapshot-test-case#131]
Thanks for the quick resolution on https://github.com/facebook/ios-snapshot-test-case/issues/125. Xcode 7.1 now shows the following warnings when 2.0.6 is installed via CocoaPods:

![screen shot 2015-10-29 at 9 32 11 am](https://cloud.githubusercontent.com/assets/494198/10824957/f9859368-7e1f-11e5-8942-ccad1af1229d.png)

I would assume it's related to this: https://github.com/CocoaPods/CocoaPods/issues/4420

**Comment by nscoding** [comment]
This should be fixed with 2.0.6 :/ Can you clean your build folder?

**Comment by soleares** [comment]
Yes, likely just an issue with switching between pre and post 2.0.6 branches. If I see if again I'll include a sample project.

**Comment by nscoding** [comment]
oh great :relieved:
