### ISSUE TITLE
Building duplicate interface declaration

### ISSUE THREAD

**Issue by HaloZero** [facebook/ios-snapshot-test-case#134]
Hi,

I have a mostly Obj-C App but I'm starting a migration to Swift so I've made all my cocoapods build as frameworks instead of static libraries. But the FBSnapshotTestCase has a problem when you try to build it as a framework.

I keep getting the error: 
Duplicate interface definition for class 'FBSnapshotTestCase'

I've set up with a testing target and set up so the project builds exclusively for that testing target.

target 'Screenshot Tests', :exclusive => true do
  pod 'FBSnapshotTestCase'
end

I've tried also installing only /Core but that doesn't work either. 

I'm not having any problems with other pods, so I'm curious if something is configured oddly on this side of things. 

I've set up a sample project here: https://github.com/HaloZero/FBSnapshotBuildError

**Comment by nscoding** [comment]
Hi,

I am not sure what exactly is going wrong here, can you try to change the import in `Screenshot_Tests.m` from:
```
#import 'FBSnapshotTestCase.h'
```
to:
```
#import <FBSnapshotTestCase/FBSnapshotTestCase.h>
```

**Comment by nscoding** [comment]
Great! I am closing the issue.
