### ISSUE TITLE
Tests fail 100% on CI

### ISSUE THREAD

**Issue by ealeksandrov** [facebook/ios-snapshot-test-case#136]
I have OS project: https://github.com/ealeksandrov/EARestrictedScrollView
Some time ago it was working well with TravisCI, but when I pushed recent changes it started to fail every time. I can't reproduce it locally even running the same command:
```
set -o pipefail && xcodebuild test -workspace Example/EARestrictedScrollView.xcworkspace -scheme EARestrictedScrollView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
```
Succeeded locally:
![screenshot 2015-12-06 00 57 46](https://cloud.githubusercontent.com/assets/3132438/11610449/66123d90-9bb4-11e5-9aac-4056c8978769.png)

Failed on TravisCI:
https://travis-ci.org/ealeksandrov/EARestrictedScrollView/builds/95062376

I even added [Second Curtain](https://github.com/ashfurrow/second_curtain) to verify images by myself, here is the result:
https://s3.amazonaws.com/hadle-travis-errors/95062377/index.html

I can't see any difference by myself, but Kaleidoscope show a lot of pixels:
![screenshot 2015-12-06 01 01 19](https://cloud.githubusercontent.com/assets/3132438/11610490/dfd57e08-9bb4-11e5-9d0f-87b1c4dd0ee2.png)

Can you suggest any ideas? Maybe 32 vs 64 bits? But TravisCI should be using the same SDK and simulator...

**Comment by nscoding** [comment]
hmm this is strange, how did you record the images at the first place (what simulator does it default to?), Your Travis CI seems to be iPhone-4s with 8.1. Is it the same when you record locally?

**Comment by ealeksandrov** [comment]
You are right. Looks like it was my mistake: `-sdk iphonesimulator9.1` doesn't mean it will use iOS 9.1.
Adding `-destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.1'` solved this issue for me.
Thanks!
