### ISSUE TITLE
SwiftSupport L63

### ISSUE THREAD

**Issue by niklassaers** [facebook/ios-snapshot-test-case#148]
When building, I get: 'Cannot convert value of type 'String' to expected argument type 'StaticString''

I have installed FBSnapshotTestCase 2.0.7 via CocoaPods, and have also tried commit ee57dee37aa5be6ee6b307670a37f9bcce69e2e4. I build with Xcode 7.3-beta3.

In my CococaPods file I have the following defined:

```
use_frameworks!
platform :ios, '8.0'
```

If I remove that line I get three errors for the following lines in FBSnapshotTestController.m:
```
#import <FBSnapshotTestCase/UIImage+Compare.h>
#import <FBSnapshotTestCase/UIImage+Diff.h>
#import <FBSnapshotTestCase/UIImage+Snapshot.h>
```

The error I get is: "Use of private header from outside its module"

When I build with Xcode 7.2.1 I don't get the StringLiteral error, but I do get the three last errors.

**Comment by niklassaers** [comment]
After reading through `[this pull request](https://github.com/facebook/ios-snapshot-test-case/pull/141)`, I see you already have got the solution for the three import errors. Please accept that pull request. :-) So it's just the line 63 error remaining. I don't know the correct solution for this, but if someone else has the same problem, my workaround for now was to comment out that lie and just write a generic XCTFail in its place.

**Comment by nscoding** [comment]
@niklassaers I am waiting for cocoapods 1.0 to go thru with the open PR.

**Comment by gregpardo** [comment]
Same issue. Waiting for cocoapods update I guess

**Comment by alper** [comment]
The entire thing does not build for me. Maybe there should be a guide how to setup a Swift project?
![rg_snapshottests swift 2016-04-22 12-05-15](https://cloud.githubusercontent.com/assets/72429/14738571/8cc46b12-0882-11e6-9aab-f1214c09349c.png)

**Comment by kuron99** [comment]
I am hitting this problem, too. Any progress or update?

**Comment by obuseme** [comment]
I'm hitting this problem as well.

**Comment by nscoding** [comment]
Still waiting on cocoapods I am afraid

**Comment by obuseme** [comment]
I was able to successfully install FBSnapshotTestCase with Carthage last night for a Swift project.  I wrote it up here if anyone is interested: http://cleanswifter.com/fbsnapshottestcase-installation-carthage/

**Comment by fcy** [comment]
So CocoaPods 1.0 is live what is the issue it was supposed to fix? I'm getting the same problem using it.

**Comment by nscoding** [comment]
great @fcy! I am going to close this one.
