### ISSUE TITLE
Swift 2.2 compilation error of test target

### ISSUE THREAD

**Issue by vandadschibsted** [facebook/ios-snapshot-test-case#151]
Swift 2.2 and Xcode 7.3, changed the definition of `XCTFail` function which is being used in `SwiftSupport.swift` file so that we are getting this error:

Pods/FBSnapshotTestCase/FBSnapshotTestCase/SwiftSupport.swift:63:30: Cannot convert value of type 'String' to expected argument type 'StaticString'

This is rendering the framework useless to us at the moment since we cannot even build our test target!!! Could this please be fixed as soon as possible?

**Comment by huberand** [comment]
Yeah same problem for us. We are stuck now :-1:  can't build our test target!

**Comment by soleares** [comment]
I think there's already a PR #150 up for this.

**Comment by vandadnp** [comment]
And it seems like this is part of Niklas's issue here: #148

**Comment by GabrielCartier** [comment]
+1

**Comment by nscoding** [comment]
This should now be fixed with #152, can someone confirm?

**Comment by joeblau** [comment]
@nscoding Yeah, that fix is in #152

**Comment by nscoding** [comment]
@joeblau thanks for confirming.
