### ISSUE TITLE
24 commits on master since last release

### ISSUE THREAD

**Issue by Pearapps** [facebook/ios-snapshot-test-case#154]
There are currently 24 commits on master that do not have a release yet.

We would love to pull in [this change ](https://github.com/facebook/ios-snapshot-test-case/pull/152) - however it is not in a release. We also do not want to pull directly from master in our podfile - so previous versions of our app are also attached to a version of this library.

Thanks!

**Comment by nscoding** [comment]
Thank you for opening this, yes, I am aware and I will be cutting a new spec today.

**Comment by Pearapps** [comment]
@nscoding Thank you so much!

**Comment by nscoding** [comment]
Spec is out, please let me know if that works for you.

```
  - Log messages:
    - March 28th, 08:39: Push for `FBSnapshotTestCase 2.1.0' initiated.
    - March 28th, 08:39: Push for `FBSnapshotTestCase 2.1.0' has been pushed (2.796577668 s).
```
