### ISSUE TITLE
Building scheme "FBSnapshotTestCase tvOS" keeps failing

### ISSUE THREAD

**Issue by liuxuan30** [facebook/ios-snapshot-test-case#159]
Travis log: https://travis-ci.org/danielgindi/Charts/builds/122282395

So it has been some weeks since iOS 9.3 was released. We notice Building scheme "FBSnapshotTestCase tvOS" keeps failing as below. We think it's FB's bug? Or any advice how to fix it?

```
37.38s$ cd Charts && carthage bootstrap

*** Cloning ios-snapshot-test-case

*** Skipped downloading ios-snapshot-test-case.framework binary due to the error:

	"GitHub API request failed: Maximum number of login attempts exceeded. Please try again later."

*** Checking out ios-snapshot-test-case at "2.1.0"

*** xcodebuild output can be found in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/carthage-xcodebuild.QfaPgp.log

*** Building scheme "FBSnapshotTestCase tvOS" in FBSnapshotTestCase.xcworkspace

** BUILD FAILED **

The following build commands failed:

	Ld /Users/travis/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-bxqdwtzedguggmawxzyipupldvjd/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64

(1 failure)

clang: error: linker command failed with exit code 1 (use -v to see invocation)

A shell task failed with exit code 65:

** BUILD FAILED **

The following build commands failed:

	Ld /Users/travis/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-bxqdwtzedguggmawxzyipupldvjd/Build/Products/Release-appletvos/FBSnapshotTestCase.framework/FBSnapshotTestCase normal arm64

(1 failure)
```

**Comment by nscoding** [comment]
Thanks for filing this issue, I need to investigate.

**Comment by danielgindi** [comment]
#157

**Comment by nscoding** [comment]
The issue seemed to appear with 2.1.0 but I didn't do anything different to cause these timeouts, it could be travis or github. I could potentially tag a new version with #158 and see if that resolves it but I don't have high hopes.

**Comment by liuxuan30** [comment]
@nscoding I have seen the GitHub API request failed before 2.1.0: https://github.com/danielgindi/Charts/pull/765
It seems not interfere.

**Comment by danielgindi** [comment]
Okay, now it seems that tvOS should be supported, but there's something new:
https://travis-ci.org/danielgindi/Charts

`A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/travis/build/danielgindi/Charts/Charts/Carthage/Checkouts/ios-snapshot-test-case/FBSnapshotTestCase.xcworkspace -scheme FBSnapshotTestCase tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:`

I seems like the `-scheme FBSnapshotTestCase tvOS` is being ran unescaped. There's a space in there that should be escaped. Is this a travis bug or a Facebook bug?

**Comment by adamjernst** [comment]
I'm hitting this too.
