### ISSUE TITLE
Allow configuration of test failure directory

### ISSUE THREAD

**Issue by tapi** [facebook/ios-snapshot-test-case#177]
It would be great if the test failure directory could be configured in a manner similar to the reference images directory. This would make it trivial to expose failed test images as build artifacts in CI environments without having to parse Xcode build logs.

**Comment by reidmain** [comment]
Is the environment variable `IMAGE_DIFF_DIR` what you are looking for? https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCase/FBSnapshotTestController.m#L266

**Comment by tapi** [comment]
That looks exactly like what I'm looking for. Guess all this needs is a little documentation around it.

**Comment by nscoding** [comment]
Yes, I would accept a PR that updates the documentation.
