### ISSUE TITLE
Branch or release for Swift 2.3

### ISSUE THREAD

**Issue by parski** [facebook/ios-snapshot-test-case#190]
Hello!

My team uses [Nimble-Snapshots](https://github.com/ashfurrow/Nimble-Snapshots) in our Swift 2.2 product and FBSnapshotTestCase is one of it's dependencies. We want to be able to build our product with Xcode 8 and since upgrading our code base to Swift 3.0 will be a large task we have decided to first upgrade it to Swift 2.3.

Can you make a release or branch from commit `b48e77e3397298baf1532a8e4f418197df2843c3 `? I strongly dislike pointing to a commit in Podfiles and having a separate branch for Swift 2.3 would make our Podfile less of a chore to deal with.

**Comment by nscoding** [comment]
hmm, the code on master at the moment has code for both `>3` and `2.3` doesn't this work for you guys?

**Comment by parski** [comment]
It works but the moment you commit to master our application might break. I would sleep a lot better knowing that I'm pointing to a release in my Podfile.

**Comment by nscoding** [comment]
I just cut a spec:
- September 22nd, 10:24: Push for `FBSnapshotTestCase 2.1.3' initiated.
- September 22nd, 10:24: Push for `FBSnapshotTestCase 2.1.3' has been pushed (0.38892521 s).

**Comment by yas375** [comment]
@parski why you weren't able to use the latest code of this library after Swift 3 branch was merged in? It uses `#if swift(>=3)` and it should have been working with both Swift 2.3 and Swift 3.0
