### ISSUE TITLE
iOS 7 support dropped without apparent compatibility issue?

### ISSUE THREAD

**Issue by appleguy** [facebook/ios-snapshot-test-case#196]
Hi all - and @nscoding, awesome handle!  A recent commit, d7edace, bumped the minimum iOS version to 8.0 without details on why this change was made.

This prevents AsyncDisplayKit from updating our dependency, which is a bummer because we'd like to use some new improvements without forking.

If there is a reason why 7.0 adds inconvenience to the framework's maintenance, that's understandable.  But when I check it out locally and make the change, nothing seems to break.

Any thoughts on whether this can be set back to 7.0 until a compatibility issue arises?

**Comment by nscoding** [comment]
Hey thanks for opening this issue, my problem was validating the spec to the point that I couldn't push a version. I will investigate this week.

**Comment by nscoding** [comment]
I had several validation issues with cocoapods but thankfully the latest prerelease allow me to validate a spec with iOS7.

- October 6th, 14:50: Push for `FBSnapshotTestCase 2.1.4' initiated.
- October 6th, 14:50: Push for `FBSnapshotTestCase 2.1.4' has been pushed (0.417551121 s).

**Comment by appleguy** [comment]
Thank you Patrick!
