### ISSUE TITLE
New Release Swift 3.0

### ISSUE THREAD

**Issue by YMonnier** [facebook/ios-snapshot-test-case#197]
Hello,

I Would like to know when you will put a new release on Cocoapods for Swift 3.0?

Thank you,

YM

**Comment by nscoding** [comment]
Yes, I plan to do it (this week), I usually wait for few days.

**Comment by YMonnier** [comment]
Ok perfect! Thank you :)

**Comment by reidmain** [comment]
Any chance we are getting a Swift 3 release this week?

**Comment by nscoding** [comment]
Yes, sorry for the delay I was very busy last week.

**Comment by nscoding** [comment]
- October 6th, 14:50: Push for `FBSnapshotTestCase 2.1.4' initiated.
- October 6th, 14:50: Push for `FBSnapshotTestCase 2.1.4' has been pushed (0.417551121 s).

**Comment by reidmain** [comment]
![You're awesome](https://media.giphy.com/media/ClcWrARkrq1GM/giphy.gif)

**Comment by YMonnier** [comment]
Great perfect! Thanks for your time!
