### ISSUE TITLE
Skip tests on other devices?

### ISSUE THREAD

**Issue by x2on** [facebook/ios-snapshot-test-case#36]
Hi,

has anybody a good idea to skip tests on other devices?
So if i make an view test on an iPhone i'd like to skip it on iPad.

I could do a if clause before the assert, but then Xcode runs the tests and only skip the assert.

Any idea?

**Comment by dstnbrkr** [comment]
#64 allows for multiple reference image sets. Restricting which simulators the tests run on is a job for the CI infra running snapshot tests.
