### ISSUE TITLE
View snapshots stretch text

### ISSUE THREAD

**Issue by dblock** [facebook/ios-snapshot-test-case#37]
I upgraded from 1.1 to HEAD and my snapshots that contain text look like this:

before:

![image](https://cloud.githubusercontent.com/assets/542335/2720938/df5d8cca-c575-11e3-8b07-d64e2995cb25.png)

after:

![image](https://cloud.githubusercontent.com/assets/542335/2720944/e5e410a0-c575-11e3-8d42-7c1f0a611acd.png)

These are all basic views that use auto-layout. I create them in tests and assign `.frame` to something big enough to host the text.

I'll work on a small repro, just wanted to put this up here first.

**Comment by dstnbrkr** [comment]
Closing this issue as stale - please reopen with a test case if you're still hitting it.

**Comment by orta** [comment]
Not seen it in forever, seems reasonable.

**Comment by dstnbrkr** [comment]
For posterity - my guess is that there was a view initialized with init instead of initWithFrame. The latter is the designated initializer, the former doesn't set up the CGContext correctly.

**Comment by orta** [comment]
This is definitely something that could have happened.
