### ISSUE TITLE
Support Running on Device

### ISSUE THREAD

**Issue by fcy** [facebook/ios-snapshot-test-case#41]
It would be awesome if running on device worked, I get error that the reference image doesn't exist because it is trying to access the image on the Mac.

Do you think it would be possible to bundle the reference images into the test target so that running on device would work?

**Comment by eagle-dan1349** [comment]
Any news regarding this one?
Or at least, what should copy reference images phase look like to work correctly?

**Comment by dstnbrkr** [comment]
I imagine it would need to (conditionally) copy the contents of your reference image directory. Conditionally, since you don't want to copy those images in a release.

**Comment by eagle-dan1349** [comment]
Yes, I understand, I mean, to where should I copy it and how exactly (to preserve folder structure)?
Since when I add ref images as folder reference to project and add this folder in copy resources phase in tests target it does not work.

**Comment by dstnbrkr** [comment]
I haven't looked into this at all, but the point where snapshot tests look for the reference images via a file system path would likely need to get those images from a bundle or an asset catalog instead.

**Comment by dstnbrkr** [comment]
Just to clarify, snapshots on device is a feature that needs building - not something that I'd expect to work with a few configuration changes.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by yiding** [comment]
Ability to put reference images into bundles is done (#104).
