### ISSUE TITLE
How do you handle differences in rendering between iOS7 and iOS8?

### ISSUE THREAD

**Issue by yas375** [facebook/ios-snapshot-test-case#50]
I've noticed that reference images recorded when tests were running on iOS7 are not the same when running on iOS8. Looks like there are some updates in UIKit which result in different rendering. For example on the screenshot below there is screenshot recorded on iOS7 on the left and on iOS8 on the right. Note that accessory indicator on iOS8 has less padding on the right.

![2014-09-26_1802](https://cloud.githubusercontent.com/assets/217368/4422881/29cd58f4-4590-11e4-840d-a3681fc39b54.png)

Have anybody else experiencing similar problems?

If you run unit tests again one iOS version you will be probably fine, but I'm curious what others do to be able to run unit tests on different iOS versions? Thanks in advance!

**Comment by dstnbrkr** [comment]
It's now possible to specify a reference image directory suffix so that you can keep multiple sets of reference images (i.e. one for iOS 7, another for iOS 8).
