### ISSUE TITLE
Push new version to CocoaPods Trunk

### ISSUE THREAD

**Issue by ashfurrow** [facebook/ios-snapshot-test-case#58]
Hi there! I had a commit [merged in](https://github.com/facebook/ios-snapshot-test-case/commit/77dd60b09ca8f4bd021a40024d90e2ae3077f164) about two months ago, and I'd like to rely on that commit for a CocoaPod [that I'm building](https://github.com/ashfurrow/nimble-snapshots). Could someone tag a release on or after that tag (say, 1.4.1 or something)? Then we can update the podspec to point to that new tag and @dstnbrkr can `pod trunk push` the new version to CocoaPods.

**Comment by dstnbrkr** [comment]
All set! Seems like these updates take a bit to propagate.

**Comment by ashfurrow** [comment]
Thanks! :beers:
