### ISSUE TITLE
WatchKit support?

### ISSUE THREAD

**Issue by neilkimmett** [facebook/ios-snapshot-test-case#60]
I assume theres no way to use `FBSnapshotTestCase` with `WKInterfaceController`s from WatchKit? I'm pretty certain theres no way to render a `WKInterfaceController` outside of the simulator but I may be missing something.

**Comment by orta** [comment]
To my knowledge, this cannot be done using the public API. 
That said, can you even run unit tests against a watch kit app? I'm not sure if you can run bundles against bundles

**Comment by neilkimmett** [comment]
Thats a very good point. Until now all the code in my watch app that I've been testing is actually shared code with my main app target.

**Comment by neilkimmett** [comment]
I've done some digging around in the private APIs and can't find any way to render a `WKInterfaceObject` to a `UIView` :disappointed:. I'm guessing this will have to wait until the full SDK comes out.

**Comment by dstnbrkr** [comment]
Thanks for digging @neilkimmett.
