### ISSUE TITLE
64 bit reference images should be saved to a separate directory.

### ISSUE THREAD

**Issue by sahrens** [facebook/ios-snapshot-test-case#65]
64-bit runs often render text slightly different, causing snapshot failures if run on the wrong device.

**Comment by dstnbrkr** [comment]
Same problem with different iOS versions. Recently added FBSnapshotVerifyViewWithReferenceDirectorySuffix to support these differences in general. Wrap that call with your own to map configurations to reference image directories.

Here's an example for 64 bit snapshots:

#define Suffix() \
({ \
#if __LP64__
  NSString *suffix = @"_64"; \
#else
  NSString *suffix = @""; \
#endif
})

#define VerifyView(view__, identifier__) \
{ \
FBSnapshotVerifyViewWithReferenceDirectorySuffix(view__, identifier__, Suffix(); \
}

**Comment by x2on** [comment]
I also have some macros for that, and for device format (iPhone 5, iPad 2, ...).

Would be nice if we could put this in folders without defining some macros.

**Comment by dstnbrkr** [comment]
Closing in favor of #68
