### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by squarefrog** [facebook/ios-snapshot-test-case#69]
Due to the use of macros, it is difficult to use `FBSnapshotTestCase` with Swift. Information is fairly scarce on getting it to work but it looks like [this StackOverflow answer](http://stackoverflow.com/a/29301901/816002) might be an elegant solution.

**Comment by modocache** [comment]
If you're interested in using snapshot tests in Swift quickly, I'd recommend using https://github.com/dblock/ios-snapshot-test-case-expecta or https://github.com/AshFurrow/Nimble-Snapshots. Those have dependencies on https://github.com/specta/expecta and https://github.com/Quick/Nimble, respectively, but are the simplest solution.

Personally I'd love to see Swift support added to this project--a thin wrapper would do. A pull request might get the conversation going?

**Comment by squarefrog** [comment]
Thanks, but I'm not using Expecta or Nimble: just pure `XCTest` in this project. 

I managed to get going by adding this repo as a submodule, dragging in the source files to my test target, creating a wrapper and a bridging header. It's definitely clunky, but it works.

**Comment by dstnbrkr** [comment]
Swift support (or a non-macro FBSnapshotVerify function) would be a great pull request.

**Comment by squarefrog** [comment]
:+1: Let me fork and make some changes and see what I can come up with.

**Comment by squarefrog** [comment]
I tried to get something together tonight, but I'm stumped by being unable to create snapshots:

````
Error Domain=NSCocoaErrorDomain Code=513 "The operation couldn’t be completed.
 (Cocoa error 513.)" UserInfo=0x7f83dad22d00 
{NSFilePath="$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages"/SwiftySnapshotsTests.SwiftySnapshotsTests, NSUnderlyingError=0x7f83dad22990 "The operation couldn’t be completed. Permission denied"}
````

I've not seen this issue when dragging the source files in so I wonder if its CocoaPods related.

**Comment by modocache** [comment]
The error states "permission denied". Does the file at `"$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages"/SwiftySnapshotsTests.SwiftySnapshotsTests` exist, and do you have permissions to read/write at that location?

**Comment by squarefrog** [comment]
I don't see why not. I've created a new project file. Digging into the problem further, it seems as if the `FB_REFERENCE_IMAGE_DIR` value is not being correctly substituted.

If I dig into the pod source code and hard-code the path it works fine.

**Comment by squarefrog** [comment]
OK further testing has proven that if I add the reference folder to the pod targets `GCC_PREPROCESSOR_MACROS`, it expands as expected. However, I'm unsure if this would be overwritten when a new `$ pod install` command is issued.
