### ISSUE TITLE
UIVisualEffect shows without blur

### ISSUE THREAD

**Issue by squarefrog** [facebook/ios-snapshot-test-case#70]
If your view has a `UIVisualEffectView`, then the snapshot is rendered without a blur effect. The root of this problem is that you need to wait for view updates before taking the snapshot. This is closely tied to the removal of drawViewHierarchyInRect:afterScreenUpdates in #52 

Adding in the wait for screen update fixes the snapshot's blur, while breaking the auto layout.

Is there a way to delay capturing the snapshot for an arbitrary amount of time?

**Comment by dstnbrkr** [comment]
Does spinning the run loop one tick in between initializing your view and taking the snapshot work?

**Comment by dstnbrkr** [comment]
(thinking out loud): we could have two verify methods:
- FBSnapshotVerifyView // snapshots immediately
- FBSnapshotVerifyViewWithTimeout // waits for a run loop tick before snapshotting or fails if that tick takes too long

the old renderAsLayer = YES/NO had this property somewhat clumsily and accidentally, as it also had two entirely different rendering methods. Ideally we'd have only one way to render but two ways to control timing of rendering.

**Comment by squarefrog** [comment]
I tried the following:

    let date = NSDate(timeIntervalSinceNow: 1.0)
    NSRunLoop.currentRunLoop().runUntilDate(date)

Which is roughly the equivalent of

    NSDate *date = [NSDate date];
    [[NSRunLoop currentRunLoop] runUntilDate:date];

If thats what you mean. If there is a better way to do this I'd love to know! I tried an async test with a `dispatch_after`, but that didn't seem to help.

I what you proposed would be an excellent solution. I think it'd be useful not just for blurring, but in cases where animation may happen when a view appears.

**Comment by dstnbrkr** [comment]
Got it - so when you add the delay like you have above, the test passes?

**Comment by squarefrog** [comment]
if I run the run loop it doesn't render the blur, but adding in the previous -draw..:afterScreenUpdates call does allow the blur to render. 

I should state the test is still usable, as it will always render without the blur. But sometimes it's useful to use the snapshot while developing a heavily nested view.

**Comment by Grubas7** [comment]
Have same problem ;(
Any hope to fix this?

**Comment by nscoding** [comment]
@Grubas7 could you put up an example project for me to debug this further? (or maybe @squarefrog )

**Comment by Grubas7** [comment]
@nscoding No problem, will do in the weekend.

**Comment by Grubas7** [comment]
@nscoding Here you have sample project:
https://github.com/Grubas7/blurSnapshot

Generally this is what simulator shows:
![ios simulator screen shot 18 jul 2015 13 11 44](https://cloud.githubusercontent.com/assets/9446070/8761445/42590e72-2d52-11e5-9655-14038c0dfebd.png)

and this is how snapshot looks:
![testsnapshot_blursnapshottest 2x](https://cloud.githubusercontent.com/assets/9446070/8761447/47e276bc-2d52-11e5-8039-f91e477760c9.png)

Tests pass (because always takes snapshot without blur), but it's a bit confusing.
If you need something else, please ask.

**Comment by nscoding** [comment]
Thank you so much for your time, I'll debug it today.

**Comment by nscoding** [comment]
#100 is addressing this issue, I will now close the issue but please reopen if you think otherwise.

**Comment by Grubas7** [comment]
@nscoding OK, thanks. I'll test this today or tomorrow.

**Comment by Grubas7** [comment]
@nscoding I had a problem with importing version 2.0.3
```
[!] An unexpected version directory `Categories` was encountered for the `/Users/XXXXXX/.cocoapods/repos/facebook/FBSnapshotTestCase` Pod in the `FBSnapshotTestCase` repository.
```
But after all, I have tested my demo project with `usesDrawViewHierarchyInRect = YES`, and everything worked fine!
Thank you very much!

**Comment by nscoding** [comment]
@Grubas7 oh yes, I haven't pushed 2.0.3 on cocoapods, will do later this week. I usually wait a couple of days.

Thanks for checking it!
