### ISSUE TITLE
All snapshot tests are run when running just one (non-shapshot) test in the same test bundle.

### ISSUE THREAD

**Issue by toddlee** [facebook/ios-snapshot-test-case#71]
We put normal tests and snapshot tests in the same test bundle.
When I select to run a single unit test by clicking on the diamond in front of the line number of a specific test, somehow all existing snapshot tests are run.
This doesn't happen if I select a snapshot test.

Since FBSnapshotTestCase derive from XCTestCase, I can't understand why this is happening, but it's kind of annoying since it usually takes very long to run all snapshot tests compared to unit tests.

Any idea why this is happening?

**Comment by dstnbrkr** [comment]
That is super odd, I've never seen this behavior. Maybe others have and can chime in. I'd be curious if the same behavior occurs in a brand new sample project.

**Comment by dnorcott** [comment]
I had the same issue when using the Expecta+Snapshots cocoapod. Once I dropped that and went back to good ol' FBSnapshotTestCase the issue went away. Are you using Specta or Expecta?

**Comment by dstnbrkr** [comment]
Sounds like this is likely isolated to Expecta - please reopen if you find otherwise.
