### ISSUE TITLE
Push 1.7 to CocoaPods

### ISSUE THREAD

**Issue by ashfurrow** [facebook/ios-snapshot-test-case#72]
Hi there! Congrats on the 1.7 release. Could you push it to CocoaPods trunk when you get a chance? Thanks!

**Comment by dstnbrkr** [comment]
Hi @ashfurrow - thought this was done, let me see what happened...

**Comment by dstnbrkr** [comment]
Odd, it looks like the push was successful on 4/18. Here's the output the 'pod trunk push':

  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/f5c12b083affda4e2986ae8b107e9837cf3e03da/Specs/FBSnapshotTestCase/1.7/FBSnapshotTestCase.podspec.json
  - Log messages:
    - April 18th, 18:03: Push for `FBSnapshotTestCase 1.7' initiated.
    - April 18th, 18:03: Push for `FBSnapshotTestCase 1.7' has been pushed (1.271117758 s)

Any ideas what I'm missing?

**Comment by ashfurrow** [comment]
Huh, that's very strange. 

Thanks for looking into this for me. Looks like I had a stale specs cached. 

![screen shot 2015-04-22 at 11 10 36 am](https://cloud.githubusercontent.com/assets/498212/7277854/44ca8994-e8e0-11e4-92ac-405479023f7e.png)

For anyone else, this was fixed with a `pod repo update`. Thanks @dstnbrkr!
