### ISSUE TITLE
All snapshot tests fail when updating to 1.8

### ISSUE THREAD

**Issue by reidmain** [facebook/ios-snapshot-test-case#78]
It seems like the folder where reference images are stored changed between 1.7 and 1.8.

All of my snapshot tests fail unless I rename my reference image folder from `ReferenceImages` to `ReferenceImages_64`

**Comment by nscoding** [comment]
Yes, I made this change to accommodate different architectures. In order for you to upgrade the simplest way is to update your `ReferenceImages` folders to `ReferenceImages_32` if you run your tests in 32bit or `ReferenceImages_64` if you run them in 64bit.

If you don't want to do that, you can provide your own `FBSnapshotTestCaseAppSpecificSuffixes()` and fallback to `ReferenceImages`

**Comment by reidmain** [comment]
Going forward it would probably be best to document this in some sort of change log so people using semantic versioning with CocoaPods at the very least have an idea about how to fix this issue.

**Comment by nscoding** [comment]
Yes you are right sorry for the confusion, we are missing documentation about this change. Regardless, I'll open a PR to fallback to `ReferenceImages` as a last resort.
