### ISSUE TITLE
Demo project test fails

### ISSUE THREAD

**Issue by stevemoser** [facebook/ios-snapshot-test-case#83]
Looks like an issue with FB_REFERENCE_IMAGE_DIR. I thought there was an issue on my end in my project but it looks like the demo project doesn't work (with the latest version of CocoaPods).

2015-05-17 22:43:57.424 FBSnapshotTestCaseDemo[14107:6951453] Application windows are expected to have a root view controller at the end of application launch
Test Suite 'All tests' started at 2015-05-18 02:43:57 +0000
Test Suite 'FBSnapshotTestCaseDemoTests.xctest' started at 2015-05-18 02:43:57 +0000
Test Suite 'FBSnapshotTestCaseDemoTests' started at 2015-05-18 02:43:57 +0000
Test Case '-[FBSnapshotTestCaseDemoTests testExample]' started.
/Users/stevemoser/Downloads/ios-snapshot-test-case-master/FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/FBSnapshotTestCaseDemoTests.m:32: error: -[FBSnapshotTestCaseDemoTests testExample] : ((comparisonSuccess__) is true) failed - Snapshot comparison failed: Error Domain=FBSnapshotTestControllerErrorDomain Code=1 "Unable to load reference image." UserInfo=0x7f858842ede0 {NSLocalizedFailureReason=Reference image not found. You need to run the test in record mode, NSLocalizedDescription=Unable to load reference image., FBReferenceImageFilePathKey="$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages"_32/FBSnapshotTestCaseDemoTests/testExample@2x.png}
Test Case '-[FBSnapshotTestCaseDemoTests testExample]' failed (0.002 seconds).
Test Suite 'FBSnapshotTestCaseDemoTests' failed at 2015-05-18 02:43:57 +0000.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.002 (0.005) seconds
Test Suite 'FBSnapshotTestCaseDemoTests.xctest' failed at 2015-05-18 02:43:57 +0000.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.002 (0.005) seconds
Test Suite 'All tests' failed at 2015-05-18 02:43:57 +0000.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.002 (0.006) seconds

**Comment by nscoding** [comment]
Hi, 

Thanks for your message,

- Regarding the example project, did you follow the initial instructions (https://github.com/facebook/ios-snapshot-test-case) on defining `FB_REFERENCE_IMAGE_DIR` in `GCC_PREPROCESSOR_DEFINITIONS`?

- Regarding your project, it might be the breaking [change](https://github.com/facebook/ios-snapshot-test-case/blob/master/CHANGELOG.md) and you will need to rename your `ReferenceImages` to `ReferenceImages_32`.

Let me know.

**Comment by dstnbrkr** [comment]
I see this error as well. I believe the demo project used to get it's definition of FB_REFERENCE_IMAGE_DIR from the default value in FBSnapshotTestCase.h. However, the error message is showing an un-preprocessed path - so maybe something has changed regarding how cocoapods are preprocessed. Luckily we can provide a cocoapods-friendly, default value for FB_REFERENCE_IMAGE_DIR via the podspec. I've also added the demo project to CI so we can detect these errors sooner.

**Comment by stevemoser** [comment]
It works! :+1:
