### ISSUE TITLE
Snapshot doesn't render UIApperances setups

### ISSUE THREAD

**Issue by Loadex** [facebook/ios-snapshot-test-case#91]
The snapshot render the UI without rendering view with the setup of their UIApperances selector.

[This may help](http://stackoverflow.com/questions/11471362/when-do-uiappearance-proxy-rules-get-applied-to-new-view-controller/13322872#13322872)
>According to the 2011 WWDC video introducing UIAppearance, the customizations are applied right before -layoutSubviews is called on the view.

**Comment by nscoding** [comment]
Thank you @Loadex for opening this.

The `layoutSubviews` method is called correctly but it seems that the view needs to be added on a `UIWindow` for the appearance proxy to apply the style.

I will need to spend some time to figure out a good solution but for now something like this will work:

```
  [[UISwitch appearance] setOnTintColor:[UIColor blueColor]];
  [[UISwitch appearance] setThumbTintColor:[UIColor lightGrayColor]];
  UISwitch *control = [[UISwitch alloc] init];
  control.on = YES;
  
  UIWindow *window = [[UIWindow alloc] initWithFrame:control.bounds];
  [window addSubview:control];
  FBSnapshotVerifyView(control, @"");
```

**Comment by Loadex** [comment]
@nscoding Thanks for this solution ! I will use it while waiting for your update. Your solution doesn't seem to work when appearances are used with `appearanceWhenContainedIn`. Any idea why or how to make this work ?

**Comment by nscoding** [comment]
@Loadex I will check it and get back to you.

**Comment by nscoding** [comment]
@Loadex can you give me an example how you use `appearanceWhenContainedIn` and how your test looks?

**Comment by Loadex** [comment]
Sure : 
Here is my produced screenshot : 
![testviewlayout 2x](https://cloud.githubusercontent.com/assets/1458311/8253613/e2280f98-1691-11e5-92fd-5cc6daec8ea1.png)

My view hierarchy look like : 
`UINavigationController-> HelpViewController -> HelpView -> UITableView -> LeftMenuCell (containing one UIImageView and on UILabel)`

My apperances setups are : 
```
 [UIImageView appearance].tintColor = [HHTheme pinkColor];
  [UIImageView appearanceWhenContainedIn:[LeftMenuTableViewCell class], [HelpViewController class], nil].tintColor = [HHTheme blueBlack];
    [UILabel appearanceWhenContainedIn:[LeftMenuTableViewCell class], [HelpViewController class], nil].tintColor = [HHTheme blueBlack];
[UIView appearance].tintColor = [HHTheme pinkColor];
```

My test file : 
``` 
@interface HelpViewControllerTests : FBSnapshotTestCase
@property (nonatomic, strong, readwrite) UINavigationController *nav;
@property (nonatomic, strong, readwrite) HelpViewController *vc;
@end

@implementation HelpViewControllerTests

- (void)setUp {
    [super setUp];
//    self.recordMode = YES;

    HelpViewController *vc = [[HelpViewController alloc] init];
    self.nav = [[UINavigationController alloc] initWithRootViewController:vc];
    self.vc = (HelpViewController*)self.nav.topViewController;
    self.vc.versionVM = [[AppVersionViewModel alloc] init];
    self.vc.dataSource = [[HelpViewControllerTableViewDataSource alloc] init];
    UIWindow *window = [[UIWindow alloc] initWithFrame:self.nav.view.bounds];
    [window addSubview:self.nav.view];
}

- (void)tearDown {
    [super tearDown];
    self.vc = nil;
    self.nav = nil;
}

- (void)testViewLayout {
    FBSnapshotVerifyView(self.nav.view, @"");
}
```

As you can see, the UIImageView adopt the pink color instead of the blueblack and the label is not blueblack either. Are my tests correct ?

**Comment by nscoding** [comment]
Thank for your detailed message.

- If I am not mistaken `UILabel` doesn't have tintColor property (maybe you meant `textColor`), can you try that? 
- What is the purpose of `[UIView appearance].tintColor = [HHTheme pinkColor];` ? maybe `backgroundColor` ?
- Could you also try `[window setRootViewController:self.vc]` ?

**Comment by Loadex** [comment]
@nscoding Thanks for you answer : 

> If I am not mistaken UILabel doesn't have tintColor property (maybe you meant textColor), can you try that?

The tintColor property works fine for the textcolor when i'm using the app. This change well the textColor. The TextColor property is not referenced to be compatible with the uiappearance proxy. I used this [link](http://nshipster.com/uiappearance/) to check the headers, and learn more about this. That's why I tried the tint color and it work fine this way.

> What is the purpose of [UIView appearance].tintColor = [HHTheme pinkColor]; ? maybe backgroundColor ?

Same here, the tintColor allow me to change so textColor on controls, I've set it as my default value everywhere else, what's weird is that it is not working on my labels here.



> Could you also try [window setRootViewController:self.vc] ?

Can't explain the new results here : 
![testviewlayout 2x](https://cloud.githubusercontent.com/assets/1458311/8283994/6d91c030-18f2-11e5-973d-049758ac7e81.png)
Seem that the nav bar is now no longer transparent (as you can see i had a cell hidden behind it on the previous screenshot) The nav bar is styled properly. But nothing changed on the labels in my cell view. The images have the good colors though.

I hope this help !

**Comment by nscoding** [comment]
@Loadex thanks for the update, I don't have a better solution for now other than the on above. I'll keep the issue open.

**Comment by nscoding** [comment]
#100 is addressing this issue, I will now close the issue but please reopen if you think otherwise.
